//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdbool.h>
#include <stdint.h>

// ----------------- Float Types Definitions ------------------

typedef float float32_t;
typedef long double float80_t;

// ------------------- Function Prototypes --------------------

int32_t __do_global_dtors_aux(void);
int32_t __libc_csu_fini(void);
int32_t __libc_csu_init(int32_t a1);
int32_t __stack_chk_fail_local(void);
int32_t __x86_get_pc_thunk_bx(int32_t a1);
int32_t __x86_get_pc_thunk_dx(int32_t a1);
int32_t _fini(void);
int32_t _init(void);
int32_t _start(int32_t a1);
int32_t client_error(int32_t a1, int32_t * a2, int32_t a3, int32_t a4);
int32_t deregister_tm_clones(void);
int32_t format_size(int32_t * a1, int32_t a2);
int32_t frame_dummy(void);
int32_t function_970(int32_t a1, int32_t a2, int32_t a3, int32_t * a4, int32_t a5);
int32_t function_980(void);
int32_t function_990(void);
int32_t function_9a0(int32_t a1);
int32_t function_9b0(void);
int32_t function_9c0(void);
int32_t function_9d0(void);
int32_t function_9e0(void);
int32_t function_9f0(int32_t a1, int32_t a2);
int32_t function_a00(int32_t a1);
int32_t function_a10(int32_t * a1);
int32_t function_a20(void);
int32_t function_a30(int32_t a1);
int32_t function_a40(void);
int32_t function_a50(int32_t * a1, int32_t a2, int32_t a3);
int32_t function_a60(void);
int32_t function_a70(void);
int32_t function_a80(void);
int32_t function_a90(int32_t * a1, int32_t a2);
int32_t function_aa0(void);
int32_t function_ab0(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5);
int32_t function_ac0(void);
int32_t function_ad0(int32_t a1, int32_t * a2, int32_t a3);
int32_t function_ae0(void);
int32_t function_af0(void);
int32_t function_b00(void);
int32_t function_b10(void);
int32_t function_b20(int32_t a1, int32_t * a2);
int32_t function_b30(int32_t a1, int32_t a2);
int32_t function_b40(int32_t a1);
int32_t function_b50(int32_t a1, int32_t a2, int32_t a3);
int32_t function_b60(int32_t a1, int32_t a2, int32_t a3, int32_t * a4);
int32_t function_b70(void);
int32_t function_b80(void);
int32_t function_b90(void);
int32_t function_ba0(int32_t a1);
int32_t function_ba8(void);
int32_t function_cc2(int32_t a1, int32_t * a2, int32_t a3);
int32_t handle_directory_request(int32_t a1, int32_t a2, int32_t * a3);
int32_t log_access(int32_t a1, int32_t a2, int32_t a3);
int32_t open_listenfd(int16_t a1);
int32_t parse_request(int32_t a1, int32_t * a2);
int32_t process(int32_t a1, int32_t a2);
int32_t register_tm_clones(void);
int32_t rio_readinitb(int32_t result, int32_t a2);
int32_t rio_readlineb(int32_t * a1, int32_t * a2, int32_t * a3);
int32_t serve_static(int32_t a1, int32_t a2, int32_t * a3, int32_t a4);
int32_t url_decode(int32_t a1, int32_t a2, int32_t a3);
int32_t writen(int32_t a1, int32_t a2, int32_t a3);

// --------------------- Global Variables ---------------------

int32_t g1 = 3; // 0x190
int32_t g2 = 0; // 0x200
int32_t g3 = 0; // 0x204
int32_t g4 = 0x140e0a51; // 0x220b
int32_t g5 = 0xa620240; // 0x23cb
int32_t g6; // 0x26e9
bool g7 = false; // 0x3ff
int32_t g8 = 0; // 0x400
char * g9; // 0x41d
char * g10 = "j"; // 0x42c
char * g11 = "j"; // 0xc1c
int32_t g12;

// ------------------------ Functions -------------------------

// Address range: 0x93c - 0x95f
int32_t _init(void) {
    // 0x93c
    int32_t v1; // 0x93c
    __x86_get_pc_thunk_bx(v1);
    int32_t result = 0; // 0x953
    if (*(int32_t *)(v1 + 0x36af) != 0) {
        // 0x955
        result = function_ba8();
    }
    // 0x95a
    return result;
}

// Address range: 0x970 - 0x976
int32_t function_970(int32_t a1, int32_t a2, int32_t a3, int32_t * a4, int32_t a5) {
    // 0x970
    int32_t result; // 0x970
    return result;
}

// Address range: 0x980 - 0x986
int32_t function_980(void) {
    // 0x980
    int32_t result; // 0x980
    return result;
}

// Address range: 0x990 - 0x996
int32_t function_990(void) {
    // 0x990
    int32_t result; // 0x990
    return result;
}

// Address range: 0x9a0 - 0x9a6
int32_t function_9a0(int32_t a1) {
    // 0x9a0
    int32_t result; // 0x9a0
    return result;
}

// Address range: 0x9b0 - 0x9b6
int32_t function_9b0(void) {
    // 0x9b0
    int32_t result; // 0x9b0
    return result;
}

// Address range: 0x9c0 - 0x9c6
int32_t function_9c0(void) {
    // 0x9c0
    int32_t result; // 0x9c0
    return result;
}

// Address range: 0x9d0 - 0x9d6
int32_t function_9d0(void) {
    // 0x9d0
    int32_t result; // 0x9d0
    return result;
}

// Address range: 0x9e0 - 0x9e6
int32_t function_9e0(void) {
    // 0x9e0
    int32_t result; // 0x9e0
    return result;
}

// Address range: 0x9f0 - 0x9f6
int32_t function_9f0(int32_t a1, int32_t a2) {
    // 0x9f0
    int32_t result; // 0x9f0
    return result;
}

// Address range: 0xa00 - 0xa06
int32_t function_a00(int32_t a1) {
    // 0xa00
    int32_t result; // 0xa00
    return result;
}

// Address range: 0xa10 - 0xa16
int32_t function_a10(int32_t * a1) {
    // 0xa10
    int32_t result; // 0xa10
    return result;
}

// Address range: 0xa20 - 0xa26
int32_t function_a20(void) {
    // 0xa20
    int32_t result; // 0xa20
    return result;
}

// Address range: 0xa30 - 0xa36
int32_t function_a30(int32_t a1) {
    // 0xa30
    int32_t result; // 0xa30
    return result;
}

// Address range: 0xa40 - 0xa46
int32_t function_a40(void) {
    // 0xa40
    int32_t result; // 0xa40
    return result;
}

// Address range: 0xa50 - 0xa56
int32_t function_a50(int32_t * a1, int32_t a2, int32_t a3) {
    // 0xa50
    int32_t result; // 0xa50
    return result;
}

// Address range: 0xa60 - 0xa66
int32_t function_a60(void) {
    // 0xa60
    int32_t result; // 0xa60
    return result;
}

// Address range: 0xa70 - 0xa76
int32_t function_a70(void) {
    // 0xa70
    int32_t result; // 0xa70
    return result;
}

// Address range: 0xa80 - 0xa86
int32_t function_a80(void) {
    // 0xa80
    int32_t result; // 0xa80
    return result;
}

// Address range: 0xa90 - 0xa96
int32_t function_a90(int32_t * a1, int32_t a2) {
    // 0xa90
    int32_t result; // 0xa90
    return result;
}

// Address range: 0xaa0 - 0xaa6
int32_t function_aa0(void) {
    // 0xaa0
    int32_t result; // 0xaa0
    return result;
}

// Address range: 0xab0 - 0xab6
int32_t function_ab0(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5) {
    // 0xab0
    int32_t result; // 0xab0
    return result;
}

// Address range: 0xac0 - 0xac6
int32_t function_ac0(void) {
    // 0xac0
    int32_t result; // 0xac0
    return result;
}

// Address range: 0xad0 - 0xad6
int32_t function_ad0(int32_t a1, int32_t * a2, int32_t a3) {
    // 0xad0
    int32_t result; // 0xad0
    return result;
}

// Address range: 0xae0 - 0xae6
int32_t function_ae0(void) {
    // 0xae0
    int32_t result; // 0xae0
    return result;
}

// Address range: 0xaf0 - 0xaf6
int32_t function_af0(void) {
    // 0xaf0
    int32_t result; // 0xaf0
    return result;
}

// Address range: 0xb00 - 0xb06
int32_t function_b00(void) {
    // 0xb00
    int32_t result; // 0xb00
    return result;
}

// Address range: 0xb10 - 0xb16
int32_t function_b10(void) {
    // 0xb10
    int32_t result; // 0xb10
    return result;
}

// Address range: 0xb20 - 0xb26
int32_t function_b20(int32_t a1, int32_t * a2) {
    // 0xb20
    int32_t result; // 0xb20
    return result;
}

// Address range: 0xb30 - 0xb36
int32_t function_b30(int32_t a1, int32_t a2) {
    // 0xb30
    int32_t result; // 0xb30
    return result;
}

// Address range: 0xb40 - 0xb46
int32_t function_b40(int32_t a1) {
    // 0xb40
    int32_t result; // 0xb40
    return result;
}

// Address range: 0xb50 - 0xb56
int32_t function_b50(int32_t a1, int32_t a2, int32_t a3) {
    // 0xb50
    int32_t result; // 0xb50
    return result;
}

// Address range: 0xb60 - 0xb66
int32_t function_b60(int32_t a1, int32_t a2, int32_t a3, int32_t * a4) {
    // 0xb60
    int32_t result; // 0xb60
    return result;
}

// Address range: 0xb70 - 0xb76
int32_t function_b70(void) {
    // 0xb70
    int32_t result; // 0xb70
    return result;
}

// Address range: 0xb80 - 0xb86
int32_t function_b80(void) {
    // 0xb80
    int32_t result; // 0xb80
    return result;
}

// Address range: 0xb90 - 0xb96
int32_t function_b90(void) {
    // 0xb90
    int32_t result; // 0xb90
    return result;
}

// Address range: 0xba0 - 0xba6
int32_t function_ba0(int32_t a1) {
    // 0xba0
    int32_t result; // 0xba0
    return result;
}

// Address range: 0xba8 - 0xbae
int32_t function_ba8(void) {
    // 0xba8
    int32_t result; // 0xba8
    return result;
}

// Address range: 0xbb0 - 0xc90
int main(int argc, char ** argv) {
    char ** v1 = argv;
    __x86_get_pc_thunk_bx((int32_t)&v1);
    __readgsdword(20);
    int32_t v2; // bp-292, 0xbb0
    int32_t v3 = function_a90(&v2, 256); // 0xbee
    int32_t v4; // bp-320, 0xbb0
    int32_t v5 = &v4; // 0xbf3
    int32_t v6 = v5; // 0xbb0
    int32_t * v7; // 0xbb0
    int32_t v8; // 0xbb0
    int32_t v9; // 0xbb0
    int32_t v10; // 0xbb0
    int32_t v11; // 0xbb0
    char ** v12; // 0xbd2
    switch ((int32_t)v12) {
        case 2: {
            int32_t v13 = *(int32_t *)(v11 + 4); // 0xc28
            v9 = v13;
            v10 = v5;
            if (*(char *)v13 < 58) {
                // 0xc36
                function_b60(v13, 0, 10, (int32_t *)&v1);
                v6 = v5;
                goto lab_0xc00;
            } else {
                goto lab_0xc7a;
            }
        }
        case 3: {
            // 0xc46
            function_b60(*(int32_t *)(v11 + 8), 0, 10, (int32_t *)v3);
            v6 = v5;
            if (function_9b0() == 0) {
                goto lab_0xc00;
            } else {
                int32_t v14 = v5 - 16; // 0xc66
                v7 = (int32_t *)v14;
                v8 = v14;
                goto lab_0xc63;
            }
        }
        default: {
            goto lab_0xc00;
        }
    }
  lab_0xc00:;
    int32_t * v15 = (int32_t *)(v6 - 12); // 0xc03
    *v15 = 1;
    int32_t * v16 = (int32_t *)(v6 - 16); // 0xc05
    *v16 = 13;
    function_a20();
    while (true) {
        // 0xc18
        int32_t v17; // bp-308, 0xbb0
        *v15 = (int32_t)&v17;
        *v16 = 0;
        process((int32_t)&g12, (int32_t)&g12);
    }
  lab_0xc7a:;
    int32_t v18 = v10 - 16;
    int32_t * v19 = (int32_t *)v18;
    *v19 = v9;
    v6 = v10;
    v7 = v19;
    v8 = v18;
    if (function_9b0() == 0) {
        goto lab_0xc00;
    } else {
        goto lab_0xc63;
    }
  lab_0xc63:
    // 0xc63
    *v7 = *(int32_t *)(v11 + 4);
    function_9e0();
    *v7 = 1;
    v9 = function_a40();
    v10 = v8;
    goto lab_0xc7a;
}

// Address range: 0xc90 - 0xcc2
int32_t _start(int32_t a1) {
    // 0xc90
    int32_t v1; // 0xc90
    int32_t v2 = v1;
    int32_t v3; // bp-4, 0xc90
    function_cc2(v1, &v3, v1);
    int32_t v4; // 0xc90
    function_ab0(*(int32_t *)(v2 + 0x3358), a1, &v4, v2 + 0x10a0, v2 + 0x1100);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0xcc2 - 0xcc6
int32_t function_cc2(int32_t a1, int32_t * a2, int32_t a3) {
    // 0xcc2
    int32_t result; // 0xcc2
    return result;
}

// Address range: 0xcd0 - 0xcd4
int32_t __x86_get_pc_thunk_bx(int32_t a1) {
    // 0xcd0
    int32_t result; // 0xcd0
    return result;
}

// Address range: 0xce0 - 0xd1a
int32_t deregister_tm_clones(void) {
    // 0xce0
    __x86_get_pc_thunk_dx((int32_t)&g12);
    int32_t v1; // 0xce0
    return v1 + 0x33cb;
}

// Address range: 0xd20 - 0xd67
int32_t register_tm_clones(void) {
    // 0xd20
    __x86_get_pc_thunk_dx((int32_t)&g12);
    return (int32_t)(((int32_t)"linux.so.2" + 0x322f + -0x322f - (int32_t)"linux.so.2" >> 2) + ((int32_t)"linux.so.2" + 0x322f + -0x322f - (int32_t)"linux.so.2" >> 2) / 0x80000000) >> 1;
}

// Address range: 0xd70 - 0xdb7
int32_t __do_global_dtors_aux(void) {
    // 0xd70
    int32_t v1; // 0xd70
    int32_t result = __x86_get_pc_thunk_bx(v1); // 0xd74
    char * v2 = (char *)(v1 + 0x3337); // 0xd82
    if (*v2 != 0) {
        // 0xdb2
        return result;
    }
    // 0xd8b
    if (*(int32_t *)(v1 + 0x3277) != 0) {
        // 0xd95
        function_ba0(*(int32_t *)(v1 + 0x328b));
    }
    int32_t result2 = deregister_tm_clones(); // 0xda6
    *v2 = 1;
    // 0xdb2
    return result2;
}

// Address range: 0xdc0 - 0xdc9
int32_t frame_dummy(void) {
    // 0xdc0
    return register_tm_clones();
}

// Address range: 0xdc9 - 0xdcd
int32_t __x86_get_pc_thunk_dx(int32_t a1) {
    // 0xdc9
    int32_t result; // 0xdc9
    return result;
}

// Address range: 0xdd0 - 0xde8
int32_t rio_readinitb(int32_t result, int32_t a2) {
    // 0xdd0
    *(int32_t *)result = a2;
    *(int32_t *)(result + 4) = 0;
    *(int32_t *)(result + 8) = result + 12;
    return result;
}

// Address range: 0xdf0 - 0xe57
int32_t writen(int32_t a1, int32_t a2, int32_t a3) {
    // 0xdf0
    int32_t v1; // 0xdf0
    __x86_get_pc_thunk_bx(v1);
    int32_t v2; // bp-28, 0xdf0
    int32_t v3 = &v2; // 0xdff
    if (a3 == 0) {
        // 0xe30
        return *(int32_t *)(v3 + 40);
    }
    int32_t v4 = a3; // 0xe2c
    int32_t v5 = a2; // 0xdf0
    *(int32_t *)(v3 - 8) = v4;
    *(int32_t *)(v3 - 12) = v5;
    *(int32_t *)(v3 - 16) = a1;
    uint32_t v6 = function_ac0(); // 0xe1e
    // 0xe18
    while (v6 < 1) {
        // 0xe40
        if (*(int32_t *)function_af0() != 4) {
            return -1;
        }
        *(int32_t *)(v3 - 8) = v4;
        *(int32_t *)(v3 - 12) = v5;
        *(int32_t *)(v3 - 16) = a1;
        v6 = function_ac0();
    }
    // 0xe2a
    v4 -= v6;
    v5 += v6;
    while (v4 != 0) {
        *(int32_t *)(v3 - 8) = v4;
        *(int32_t *)(v3 - 12) = v5;
        *(int32_t *)(v3 - 16) = a1;
        v6 = function_ac0();
        // 0xe18
        while (v6 < 1) {
            // 0xe40
            if (*(int32_t *)function_af0() != 4) {
                return -1;
            }
            *(int32_t *)(v3 - 8) = v4;
            *(int32_t *)(v3 - 12) = v5;
            *(int32_t *)(v3 - 16) = a1;
            v6 = function_ac0();
        }
        // 0xe2a
        v4 -= v6;
        v5 += v6;
    }
    // 0xe30
    return *(int32_t *)(v3 + 40);
}

// Address range: 0xe60 - 0xf5b
int32_t rio_readlineb(int32_t * a1, int32_t * a2, int32_t * a3) {
    // 0xe60
    int32_t v1; // 0xe60
    __x86_get_pc_thunk_bx(v1);
    int32_t v2; // bp-44, 0xe60
    int32_t v3 = &v2; // 0xe6f
    int32_t * v4; // 0xe60
    int32_t * v5; // 0xe60
    int32_t * v6; // 0xe60
    int32_t * v7; // 0xe60
    int32_t v8; // 0xeb3
    int32_t v9; // 0xe60
    int32_t v10; // 0xe87
    int32_t * v11; // 0xea0
    if (a3 < (int32_t *)2) {
        // 0xe60
        v4 = (int32_t *)(v3 + 8);
        v5 = (int32_t *)(v3 + 52);
    } else {
        // 0xe83
        v9 = (int32_t)a1;
        v10 = v9 + 12;
        v11 = (int32_t *)(v9 + 4);
        v6 = (int32_t *)(v3 + 52);
        v7 = (int32_t *)(v3 + 8);
        while (true) {
          lab_0xea0:;
            int32_t v12 = *v11;
            while (v12 >= 0 != v12 != 0) {
                // 0xea7
                *(int32_t *)(v3 - 8) = (int32_t)&g8;
                *(int32_t *)(v3 - 12) = v10;
                *(int32_t *)(v3 - 16) = *a1;
                v8 = function_990();
                *v11 = v8;
                if (v8 >= 0) {
                    if (v8 == 0) {
                        // 0xf40
                        v4 = v7;
                        v5 = v6;
                        if (*v7 != 1) {
                            goto lab_0xf00_3;
                        } else {
                            // 0xf47
                            *v7 = 0;
                            int32_t v13 = 0; // 0xf4f
                            return *v4;
                        }
                    } else {
                        // 0xec6
                        int32_t * v14; // 0xe60
                        *v14 = v10;
                        goto lab_0xecd;
                    }
                }
                // 0xf18
                if (*(int32_t *)function_af0() != 4) {
                    // 0xf22
                    *v7 = -1;
                    return -1;
                }
                v12 = v8;
            }
            // 0xecd
            goto lab_0xecd;
        }
    }
    goto lab_0xf00_3;
  lab_0xecd:
    // 0xecd
    *v6 = *v6 + 1;
    char v15 = *(char *)v10; // 0xed8
    *(int32_t *)(v9 + 8) = v10 + 1;
    *v11 = v8 - 1;
    *(char *)(*v6 - 1) = v15;
    v4 = v7;
    v5 = v6;
    if (v15 == 10) {
        // break -> 0xf00
        goto lab_0xf00_3;
    }
    // 0xef0
    *v7 = *v7 + 1;
    v4 = v7;
    v5 = v6;
    if (*v6 == *(int32_t *)(v3 + 12)) {
        // break -> 0xf00
        goto lab_0xf00_3;
    }
    goto lab_0xea0;
  lab_0xf00_3:
    // 0xf00
    *(char *)*v5 = 0;
  lab_0xf07:
    // 0xf07
    return *v4;
}

// Address range: 0xf60 - 0x1044
int32_t format_size(int32_t * a1, int32_t a2) {
    int32_t v1 = (int32_t)a1;
    int32_t v2; // 0xf60
    __x86_get_pc_thunk_bx(v2);
    if ((*(int32_t *)(a2 + 16) & 0xf000) == 0x4000) {
        // 0x1030
        *a1 = 0x5249445b;
        *(int16_t *)(v1 + 4) = 93;
        return 93;
    }
    int32_t v3 = *(int32_t *)(a2 + 44); // 0xf8a
    int32_t v4; // 0xf60
    int32_t v5; // bp-44, 0xf60
    if (v3 > (int32_t)&g7) {
        float80_t v6 = (float80_t)*(float32_t *)(v2 + 0x116a); // 0xf94
        float80_t v7 = (float80_t)v3 * v6; // 0xfa7
        if (v3 < 0x100000) {
            // 0xff0
            v5 = (float32_t)v7;
            v4 = v2 + 3706;
        } else {
            float80_t v8 = v7 * v6; // 0xfb0
            if (v3 < 0x40000000) {
                // 0x1010
                v5 = (float32_t)v8;
                v4 = v2 + 3712;
            } else {
                // 0xfb4
                v5 = (float32_t)(v8 * v6);
                v4 = v2 + 3718;
            }
        }
    } else {
        // 0xfe0
        v5 = v3;
        v4 = v2 + 3898;
    }
    int32_t v9 = &v5;
    *(int32_t *)(v9 - 4) = v4;
    *(int32_t *)(v9 - 8) = -1;
    *(int32_t *)(v9 - 12) = 1;
    *(int32_t *)(v9 - 16) = v1;
    return function_b90();
}

// Address range: 0x1050 - 0x1360
int32_t handle_directory_request(int32_t a1, int32_t a2, int32_t * a3) {
    // 0x1050
    int32_t v1; // 0x1050
    __x86_get_pc_thunk_bx(v1);
    int32_t v2 = __readgsdword(20); // 0x1067
    int32_t v3; // bp-1056, 0x1050
    int32_t v4 = &v3; // 0x10a9
    function_b90();
    int32_t v5 = v4;
    int32_t v6 = *(int32_t *)v5; // 0x10b9
    int32_t v7 = v5 + 4; // 0x10bb
    int32_t v8 = v6 - 0x1010101 & (v6 ^ -0x7f7f7f80); // 0x10c6
    uint32_t v9 = v8 & -0x7f7f7f80; // 0x10c8
    while (v9 == 0) {
        // 0x10b9
        v5 = v7;
        v6 = *(int32_t *)v5;
        v7 = v5 + 4;
        v8 = v6 - 0x1010101 & (v6 ^ -0x7f7f7f80);
        v9 = v8 & -0x7f7f7f80;
    }
    int32_t v10 = (v8 & 0x8080) == 0 ? v5 + 6 : v7; // 0x10df
    unsigned char v11 = (char)((v8 & 0x8080) == 0 ? v9 / 0x10000 : v9); // 0x10e4
    writen(a1, v4, v10 - v4 + (-1 - v11 < v11 ? -4 : -3));
    int32_t v12 = function_b40(a2); // 0x1102
    int32_t v13; // bp-1228, 0x1050
    int32_t v14 = &v13; // 0x1113
    int32_t * v15 = (int32_t *)(v14 - 16); // 0x1133
    *v15 = v12;
    int32_t v16 = function_b10(); // 0x1139
    int32_t * v17; // 0x1050
    int32_t * v18; // 0x1050
    if (v16 == 0) {
        // 0x10cf
        v18 = (int32_t *)(v14 - 12);
        v17 = (int32_t *)(v14 - 8);
    } else {
        // 0x1149
        bool v19; // 0x1050
        int32_t v20 = v19 ? -1 : 1;
        int32_t * v21 = (int32_t *)(v14 - 8);
        int32_t * v22 = (int32_t *)(v14 - 12);
        int32_t v23; // bp-1192, 0x1050
        int32_t v24 = &v23;
        int32_t * v25 = (int32_t *)(v14 - 20);
        int32_t * v26 = (int32_t *)(v14 - 24);
        int32_t * v27 = (int32_t *)(v14 - 28);
        int32_t * v28 = (int32_t *)(v14 - 32);
        int32_t v29; // bp-1088, 0x1050
        int32_t v30 = &v29;
        int32_t v31; // bp-1104, 0x1050
        int32_t v32 = &v31;
        int32_t v33 = v1 & 0xf000;
        int32_t v34 = v1 + 0x2ef9 + (v33 != 0x4000 ? -0x2040 : -0x2162);
        int32_t v35 = v16 + 11; // 0x114f
        int32_t v36 = 2; // 0x115d
        int32_t v37 = v35;
        int32_t v38 = v1 + 3613;
        unsigned char v39 = *(char *)v37; // 0x115d
        char v40 = *(char *)v38; // 0x115d
        char v41 = v40; // 0x115d
        bool v42 = false; // 0x115d
        int32_t v43; // 0x1050
        int32_t v44; // 0x1050
        while (v39 == v40) {
            v36--;
            v43 = v38 + v20;
            v44 = v37 + v20;
            v41 = v39;
            v42 = true;
            if (v36 == 0) {
                // break -> 
                break;
            }
            v37 = v44;
            v38 = v43;
            v39 = *(char *)v37;
            v40 = *(char *)v38;
            v41 = v40;
            v42 = false;
        }
        unsigned char v45 = v41;
        int32_t v46 = v35; // 0x1166
        int32_t v47 = 3; // 0x1166
        char v48; // 0x1050
        unsigned char v49; // 0x1050
        int32_t v50; // 0x1050
        int32_t v51; // 0x1050
        int32_t v52; // 0x1050
        int32_t v53; // 0x1050
        int32_t v54; // bp-1128, 0x1050
        unsigned char v55; // 0x1179
        char v56; // 0x1179
        int32_t v57; // 0x1179
        int32_t v58; // 0x1192
        int32_t v59; // 0x1262
        int32_t v60; // 0x1264
        int32_t v61; // 0x126f
        uint32_t v62; // 0x1271
        unsigned char v63; // 0x128d
        bool v64; // 0x1050
        if ((v39 >= v45 && !v42) != v39 < v45) {
            v53 = v46;
            v51 = v1 + 3612;
            v55 = *(char *)v53;
            v56 = *(char *)v51;
            v48 = v56;
            v64 = false;
            while (v55 == v56) {
                // 0x1168
                v57 = v47 - 1;
                v50 = v51 + v20;
                v46 = v53 + v20;
                v47 = v57;
                v48 = v55;
                v64 = true;
                if (v57 == 0) {
                    // break -> 
                    break;
                }
                v53 = v46;
                v51 = v50;
                v55 = *(char *)v53;
                v56 = *(char *)v51;
                v48 = v56;
                v64 = false;
            }
            v49 = v48;
            if ((v55 >= v49 && !v64) != v55 < v49) {
                // 0x1184
                *v21 = 0;
                *v22 = v35;
                *v15 = a2;
                v58 = function_9c0();
                if (v58 == -1) {
                    // 0x1340
                    *v15 = v35;
                    function_9e0();
                } else {
                    // 0x11a5
                    *v21 = v24;
                    *v22 = v58;
                    *v15 = 3;
                    function_a10(&v23);
                    *v15 = (int32_t)&v54;
                    *v25 = function_a70();
                    *v26 = v1 + 3615;
                    *v27 = 32;
                    *v28 = v30;
                    function_a60();
                    *v22 = v24;
                    *v15 = v32;
                    format_size(&v31, (int32_t)&g12);
                    if ((v33 - 0x4000 & -0x5000) == 0) {
                        // 0x121d
                        *v22 = v32;
                        *v15 = v30;
                        *v25 = v34;
                        *v26 = v35;
                        *v27 = v34;
                        *v28 = v35;
                        *(int32_t *)(v14 - 36) = v1 + 4069;
                        *(int32_t *)(v14 - 40) = (int32_t)&g8;
                        *(int32_t *)(v14 - 44) = 1;
                        *(int32_t *)(v14 - 48) = v4;
                        function_b90();
                        v52 = v4;
                        v59 = *(int32_t *)v52;
                        v60 = v52 + 4;
                        v61 = v59 - 0x1010101 & (v59 ^ -0x7f7f7f80);
                        v62 = v61 & -0x7f7f7f80;
                        while (v62 == 0) {
                            // 0x1262
                            v52 = v60;
                            v59 = *(int32_t *)v52;
                            v60 = v52 + 4;
                            v61 = v59 - 0x1010101 & (v59 ^ -0x7f7f7f80);
                            v62 = v61 & -0x7f7f7f80;
                        }
                        // 0x1278
                        v63 = (char)((v61 & 0x8080) == 0 ? v62 / 0x10000 : v62);
                        *v21 = ((v61 & 0x8080) == 0 ? v52 + 6 : v60) - v4 + (-1 - v63 < v63 ? -4 : -3);
                        *v22 = v4;
                        *v15 = a1;
                        writen((int32_t)&g12, (int32_t)&g12, (int32_t)&g12);
                    }
                    // 0x12aa
                    *v15 = v58;
                    function_b70();
                }
            }
        }
        // 0x1130
        *v15 = v12;
        int32_t v65 = function_b10(); // 0x1139
        v18 = v22;
        v17 = v21;
        while (v65 != 0) {
            // 0x1149
            v35 = v65 + 11;
            v36 = 2;
            v37 = v35;
            v38 = v1 + 3613;
            v39 = *(char *)v37;
            v40 = *(char *)v38;
            v41 = v40;
            v42 = false;
            while (v39 == v40) {
                v36--;
                v43 = v38 + v20;
                v44 = v37 + v20;
                v41 = v39;
                v42 = true;
                if (v36 == 0) {
                    // break -> 
                    break;
                }
                v37 = v44;
                v38 = v43;
                v39 = *(char *)v37;
                v40 = *(char *)v38;
                v41 = v40;
                v42 = false;
            }
            v45 = v41;
            v46 = v35;
            v47 = 3;
            if ((v39 >= v45 && !v42) != v39 < v45) {
                v53 = v46;
                v51 = v1 + 3612;
                v55 = *(char *)v53;
                v56 = *(char *)v51;
                v48 = v56;
                v64 = false;
                while (v55 == v56) {
                    // 0x1168
                    v57 = v47 - 1;
                    v50 = v51 + v20;
                    v46 = v53 + v20;
                    v47 = v57;
                    v48 = v55;
                    v64 = true;
                    if (v57 == 0) {
                        // break -> 
                        break;
                    }
                    v53 = v46;
                    v51 = v50;
                    v55 = *(char *)v53;
                    v56 = *(char *)v51;
                    v48 = v56;
                    v64 = false;
                }
                v49 = v48;
                if ((v55 >= v49 && !v64) != v55 < v49) {
                    // 0x1184
                    *v21 = 0;
                    *v22 = v35;
                    *v15 = a2;
                    v58 = function_9c0();
                    if (v58 == -1) {
                        // 0x1340
                        *v15 = v35;
                        function_9e0();
                    } else {
                        // 0x11a5
                        *v21 = v24;
                        *v22 = v58;
                        *v15 = 3;
                        function_a10(&v23);
                        *v15 = (int32_t)&v54;
                        *v25 = function_a70();
                        *v26 = v1 + 3615;
                        *v27 = 32;
                        *v28 = v30;
                        function_a60();
                        *v22 = v24;
                        *v15 = v32;
                        format_size(&v31, (int32_t)&g12);
                        if ((v33 - 0x4000 & -0x5000) == 0) {
                            // 0x121d
                            *v22 = v32;
                            *v15 = v30;
                            *v25 = v34;
                            *v26 = v35;
                            *v27 = v34;
                            *v28 = v35;
                            *(int32_t *)(v14 - 36) = v1 + 4069;
                            *(int32_t *)(v14 - 40) = (int32_t)&g8;
                            *(int32_t *)(v14 - 44) = 1;
                            *(int32_t *)(v14 - 48) = v4;
                            function_b90();
                            v52 = v4;
                            v59 = *(int32_t *)v52;
                            v60 = v52 + 4;
                            v61 = v59 - 0x1010101 & (v59 ^ -0x7f7f7f80);
                            v62 = v61 & -0x7f7f7f80;
                            while (v62 == 0) {
                                // 0x1262
                                v52 = v60;
                                v59 = *(int32_t *)v52;
                                v60 = v52 + 4;
                                v61 = v59 - 0x1010101 & (v59 ^ -0x7f7f7f80);
                                v62 = v61 & -0x7f7f7f80;
                            }
                            // 0x1278
                            v63 = (char)((v61 & 0x8080) == 0 ? v62 / 0x10000 : v62);
                            *v21 = ((v61 & 0x8080) == 0 ? v52 + 6 : v60) - v4 + (-1 - v63 < v63 ? -4 : -3);
                            *v22 = v4;
                            *v15 = a1;
                            writen((int32_t)&g12, (int32_t)&g12, (int32_t)&g12);
                        }
                        // 0x12aa
                        *v15 = v58;
                        function_b70();
                    }
                }
            }
            // 0x1130
            *v15 = v12;
            v65 = function_b10();
            v18 = v22;
            v17 = v21;
        }
    }
    // 0x12c0
    v3 = 0x61742f3c;
    *v17 = 22;
    *v18 = v4;
    *v15 = a1;
    writen(v3, 0x3e656c62, 0x6f622f3c);
    *v15 = v12;
    function_b80();
    int32_t result = __readgsdword(20) ^ v2; // 0x132a
    if (result != 0) {
        // 0x1356
        return __stack_chk_fail_local();
    }
    // 0x1333
    return result;
}

// Address range: 0x1360 - 0x1460
int32_t open_listenfd(int16_t a1) {
    // 0x1360
    int32_t v1; // 0x1360
    __x86_get_pc_thunk_bx(v1);
    __readgsdword(20);
    int32_t v2 = 1; // bp-36, 0x137d
    int32_t v3 = function_b50(2, 1, 0); // 0x138b
    int32_t result; // 0x1360
    if (v3 < 0) {
        // 0x1448
        result = -1;
        goto lab_0x142f;
    } else {
        // 0x139b
        if (function_970(v3, 1, 2, &v2, 4) < 0) {
            // 0x1448
            result = -1;
            goto lab_0x142f;
        } else {
            // 0x13bc
            if (function_970(v3, 6, 3, &v2, 4) < 0) {
                // 0x1448
                result = -1;
                goto lab_0x142f;
            } else {
                int32_t v4 = 2; // bp-32, 0x13e4
                if (function_ad0(v3, &v4, 16) < 0) {
                    // 0x1448
                    result = -1;
                    goto lab_0x142f;
                } else {
                    int32_t v5 = function_b20(v3, &g8); // 0x1423
                    result = v3;
                    if (v5 < 0) {
                        // 0x1448
                        result = -1;
                        goto lab_0x142f;
                    } else {
                        goto lab_0x142f;
                    }
                }
            }
        }
    }
  lab_0x142f:;
    // 0x142f
    int32_t v6; // bp-44, 0x1360
    if (*(int32_t *)((int32_t)&v6 + 28) != __readgsdword(20)) {
        // 0x144f
        return __stack_chk_fail_local();
    }
    // 0x143e
    return result;
}

// Address range: 0x1460 - 0x1510
int32_t url_decode(int32_t a1, int32_t a2, int32_t a3) {
    // 0x1460
    int32_t v1; // 0x1460
    __x86_get_pc_thunk_bx(v1);
    int32_t v2; // bp-60, 0x1460
    int32_t v3 = &v2; // 0x146f
    __readgsdword(20);
    char v4 = *(char *)a1; // 0x14a2
    int32_t v5 = a2; // 0x14a7
    if (v4 != 0) {
        int32_t v6 = a2 - 1 + a3; // 0x1496
        int32_t v7 = a2;
        v5 = v6;
        if (v7 == v6) {
            // break (via goto) -> 0x14c1
            goto lab_0x14c1_2;
        }
        int32_t v8 = a1;
        char v9 = v4;
        int32_t v10 = v7 + 1; // 0x14ad
        int32_t v11 = v8 + 1;
        char v12; // 0x14ba
        while (v9 != 37) {
            // 0x14b4
            *(char *)v7 = v9;
            v12 = *(char *)v11;
            v5 = v10;
            if (v12 == 0) {
                // break (via goto) -> 0x14c1
                goto lab_0x14c1_2;
            }
            v7 = v10;
            v5 = v6;
            if (v7 == v6) {
                // break (via goto) -> 0x14c1
                goto lab_0x14c1_2;
            }
            // 0x14ad
            v8 = v11;
            v9 = v12;
            v10 = v7 + 1;
            v11 = v8 + 1;
        }
        int32_t v13 = v8 + 3; // 0x14e7
        *(int16_t *)(v3 + 25) = *(int16_t *)v11;
        *(int32_t *)(v3 - 8) = 16;
        *(int32_t *)(v3 - 12) = 0;
        *(int32_t *)(v3 - 16) = *(int32_t *)(v3 + 12);
        *(char *)v7 = (char)function_a80();
        char v14 = *(char *)v13; // 0x14a2
        v5 = v10;
        while (v14 != 0) {
            // 0x14a9
            v7 = v10;
            v5 = v6;
            if (v7 == v6) {
                // break (via goto) -> 0x14c1
                goto lab_0x14c1_2;
            }
            // 0x14ad
            v8 = v13;
            v9 = v14;
            v10 = v7 + 1;
            v11 = v8 + 1;
            while (v9 != 37) {
                // 0x14b4
                *(char *)v7 = v9;
                v12 = *(char *)v11;
                v5 = v10;
                if (v12 == 0) {
                    // break (via goto) -> 0x14c1
                    goto lab_0x14c1_2;
                }
                v7 = v10;
                v5 = v6;
                if (v7 == v6) {
                    // break (via goto) -> 0x14c1
                    goto lab_0x14c1_2;
                }
                // 0x14ad
                v8 = v11;
                v9 = v12;
                v10 = v7 + 1;
                v11 = v8 + 1;
            }
            // 0x14e0
            v13 = v8 + 3;
            *(int16_t *)(v3 + 25) = *(int16_t *)v11;
            *(int32_t *)(v3 - 8) = 16;
            *(int32_t *)(v3 - 12) = 0;
            *(int32_t *)(v3 - 16) = *(int32_t *)(v3 + 12);
            *(char *)v7 = (char)function_a80();
            v14 = *(char *)v13;
            v5 = v10;
        }
    }
  lab_0x14c1_2:;
    int32_t result = __readgsdword(20) ^ *(int32_t *)(v3 + 28); // 0x14c5
    *(char *)v5 = 0;
    if (result != 0) {
        // 0x1504
        return __stack_chk_fail_local();
    }
    // 0x14d1
    return result;
}

// Address range: 0x1510 - 0x16d0
int32_t parse_request(int32_t a1, int32_t * a2) {
    int32_t v1 = (int32_t)a2;
    int32_t v2; // 0x1510
    __x86_get_pc_thunk_bx(v2);
    __readgsdword(20);
    int32_t v3 = a1; // bp-4140, 0x154e
    *(int32_t *)(v1 + (int32_t)&g2) = 0;
    int32_t * v4 = (int32_t *)(v1 + (int32_t)&g3); // 0x1563
    *v4 = 0;
    int32_t v5; // bp-3104, 0x1510
    rio_readlineb(&v3, &v5, &g8);
    function_ae0();
    int32_t v6; // bp-4156, 0x1510
    int32_t v7 = &v6; // 0x15b3
    if (v5 % 256 != 10) {
        int32_t v8 = &v5; // 0x1576
        char * v9 = (char *)(v7 + (int32_t)&g9); // 0x15c8
        int32_t * v10 = (int32_t *)(v7 - 8);
        int32_t * v11 = (int32_t *)(v7 - 12);
        int32_t * v12 = (int32_t *)(v7 - 16);
        while (*v9 != 10) {
            // 0x15c8
            *v10 = (int32_t)&g8;
            *v11 = v8;
            *v12 = (int32_t)&v3;
            rio_readlineb(&g12, &g12, &g12);
            char v13 = *(char *)(v7 + (int32_t)&g10 - 16); // 0x15e1
            while (v13 == 82) {
                // 0x15f0
                if (*(char *)(v7 + 1053) == 97) {
                    // 0x15fa
                    if (*(char *)(v7 + 1054) == 110) {
                        // 0x1604
                        *(int32_t *)(v7 - 4) = *(int32_t *)(v7 + 8);
                        *v10 = *(int32_t *)(v7 + 12);
                        *v11 = v2 + 2422;
                        *v12 = v8;
                        function_ae0();
                        int32_t v14 = *v4; // 0x1619
                        if (v14 != 0) {
                            // 0x1626
                            *v4 = v14 + 1;
                        }
                        // 0x162f
                        if (*(char *)(v7 + 1052) == 10) {
                            // break (via goto) -> 0x1640
                            goto lab_0x1640_2;
                        }
                    }
                }
                // 0x15c8
                if (*v9 == 10) {
                    // break (via goto) -> 0x1640
                    goto lab_0x1640_2;
                }
                *v10 = (int32_t)&g8;
                *v11 = v8;
                *v12 = (int32_t)&v3;
                rio_readlineb(&g12, &g12, &g12);
                v13 = *(char *)(v7 + (int32_t)&g10 - 16);
            }
            if (v13 == 10) {
                // break -> 0x1640
                break;
            }
        }
    }
  lab_0x1640_2:;
    int32_t * v15 = (int32_t *)(v7 + 4); // 0x1648
    int32_t * v16; // 0x1510
    int32_t v17; // 0x1510
    if (*(char *)(v7 + (int32_t)&g11) == 47) {
        int32_t v18 = v7 + 3101; // 0x1683
        int32_t * v19 = (int32_t *)(v7 - 16);
        *v19 = v18;
        uint32_t v20 = function_aa0(); // 0x168b
        v16 = v19;
        v17 = v2 + 2399;
        if (v20 != 0) {
            int32_t v21 = v18;
            char * v22 = (char *)v21;
            while (*v22 != 63) {
                // 0x16ad
                v16 = v19;
                v17 = v18;
                if (v20 <= v21 - *v15) {
                    goto lab_0x164e;
                }
                v21++;
                v22 = (char *)v21;
            }
            // 0x16c0
            *v22 = 0;
            v16 = v19;
            v17 = v18;
        }
    } else {
        // 0x1640
        v16 = (int32_t *)(v7 - 16);
        v17 = *v15;
    }
  lab_0x164e:
    // 0x164e
    *(int32_t *)(v7 - 8) = (int32_t)&g8;
    *(int32_t *)(v7 - 12) = v1;
    *v16 = v17;
    url_decode((int32_t)&g12, (int32_t)&g12, (int32_t)&g12);
    int32_t result = __readgsdword(20) ^ *(int32_t *)(v7 + 0x101c); // 0x1667
    if (result != 0) {
        // 0x16c7
        return __stack_chk_fail_local();
    }
    // 0x1670
    return result;
}

// Address range: 0x16d0 - 0x1717
int32_t log_access(int32_t a1, int32_t a2, int32_t a3) {
    // 0x16d0
    int32_t v1; // 0x16d0
    __x86_get_pc_thunk_bx(v1);
    function_9a0(*(int32_t *)(a2 + 4));
    return function_b00();
}

// Address range: 0x1720 - 0x1860
int32_t client_error(int32_t a1, int32_t * a2, int32_t a3, int32_t a4) {
    // 0x1720
    int32_t v1; // bp-1056, 0x1720
    int32_t v2 = &v1; // 0x1726
    int32_t v3; // 0x1720
    __x86_get_pc_thunk_bx(v3);
    int32_t v4 = __readgsdword(20); // 0x1743
    function_b90();
    function_aa0();
    int32_t v5 = v2; // 0x1777
    int32_t v6 = *(int32_t *)v5; // 0x1779
    v5 += 4;
    while (((v6 & -0x7f7f7f80 ^ -0x7f7f7f80) & v6 - 0x1010101) == 0) {
        // 0x1779
        v6 = *(int32_t *)v5;
        v5 += 4;
    }
    // 0x1790
    function_b90();
    int32_t v7 = v2;
    int32_t v8 = *(int32_t *)v7; // 0x17c7
    int32_t v9 = v7 + 4; // 0x17c9
    int32_t v10 = v8 - 0x1010101 & (v8 ^ -0x7f7f7f80); // 0x17d4
    uint32_t v11 = v10 & -0x7f7f7f80; // 0x17d6
    while (v11 == 0) {
        // 0x17c7
        v7 = v9;
        v8 = *(int32_t *)v7;
        v9 = v7 + 4;
        v10 = v8 - 0x1010101 & (v8 ^ -0x7f7f7f80);
        v11 = v10 & -0x7f7f7f80;
    }
    unsigned char v12 = (char)((v10 & 0x8080) == 0 ? v11 / 0x10000 : v11); // 0x17f2
    function_9f0(((v10 & 0x8080) == 0 ? v7 + 6 : v9) - (-1 - v12 < v12 ? 4 : 3), a4);
    int32_t v13 = v2;
    int32_t v14 = *(int32_t *)v13; // 0x1803
    int32_t v15 = v13 + 4; // 0x1805
    int32_t v16 = v14 - 0x1010101 & (v14 ^ -0x7f7f7f80); // 0x1810
    uint32_t v17 = v16 & -0x7f7f7f80; // 0x1812
    while (v17 == 0) {
        // 0x1803
        v13 = v15;
        v14 = *(int32_t *)v13;
        v15 = v13 + 4;
        v16 = v14 - 0x1010101 & (v14 ^ -0x7f7f7f80);
        v17 = v16 & -0x7f7f7f80;
    }
    int32_t v18 = (v16 & 0x8080) == 0 ? v13 + 6 : v15; // 0x182b
    unsigned char v19 = (char)((v16 & 0x8080) == 0 ? v17 / 0x10000 : v17); // 0x182e
    writen(a1, v2, v18 - v2 + (-1 - v19 < v19 ? -4 : -3));
    int32_t result = __readgsdword(20) ^ v4; // 0x1848
    if (result != 0) {
        // 0x1859
        return __stack_chk_fail_local();
    }
    // 0x1851
    return result;
}

// Address range: 0x1860 - 0x1b80
int32_t serve_static(int32_t a1, int32_t a2, int32_t * a3, int32_t a4) {
    int32_t v1 = (int32_t)a3;
    int32_t v2; // 0x1860
    __x86_get_pc_thunk_bx(v2);
    int32_t v3 = __readgsdword(20); // 0x187a
    int32_t * v4 = (int32_t *)(v1 + (int32_t)&g2); // 0x1885
    int32_t v5 = 0x50545448; // bp-288, 0x1891
    if (*v4 >= 1) {
        // 0x18ad
        function_b90();
    }
    // 0x1905
    int32_t v6; // bp-316, 0x1860
    int32_t v7 = &v6; // 0x1871
    int32_t v8 = &v5; // 0x190b
    int32_t v9 = v8;
    int32_t v10 = *(int32_t *)v9; // 0x1913
    int32_t v11 = v9 + 4; // 0x1915
    int32_t v12 = v10 - 0x1010101 & (v10 ^ -0x7f7f7f80); // 0x1920
    uint32_t v13 = v12 & -0x7f7f7f80; // 0x1922
    while (v13 == 0) {
        // 0x1913
        v9 = v11;
        v10 = *(int32_t *)v9;
        v11 = v9 + 4;
        v12 = v10 - 0x1010101 & (v10 ^ -0x7f7f7f80);
        v13 = v12 & -0x7f7f7f80;
    }
    unsigned char v14 = (char)((v12 & 0x8080) == 0 ? v13 / 0x10000 : v13); // 0x194a
    int32_t v15 = ((v12 & 0x8080) == 0 ? v9 + 6 : v11) - (-1 - v14 < v14 ? 4 : 3); // 0x1951
    *(int16_t *)(v15 + 24) = 10;
    *(int32_t *)v15 = 0x68636143;
    *(int32_t *)(v15 + 4) = 0x6f432d65;
    *(int32_t *)(v15 + 8) = 0x6f72746e;
    *(int32_t *)(v15 + 12) = 0x6e203a6c;
    *(int32_t *)(v15 + 16) = 0x61632d6f;
    *(int32_t *)(v15 + 20) = 0xd656863;
    function_b90();
    int32_t v16 = function_b30(v1, 46); // 0x19b1
    int32_t v17; // 0x1860
    if (v16 == 0) {
        // 0x1a00
        v17 = v2 + (int32_t)&g6 + 204;
        goto lab_0x1a06;
    } else {
        int32_t v18 = v2 + (int32_t)&g6 + 236; // 0x19bf
        int32_t v19 = *(int32_t *)v18; // 0x19bf
        if (v19 == 0) {
            // 0x1a00
            v17 = v2 + (int32_t)&g6 + 204;
            goto lab_0x1a06;
        } else {
            int32_t v20 = v18;
            *(int32_t *)(v7 - 12) = v16;
            *(int32_t *)(v7 - 16) = v19;
            while (function_980() != 0) {
                int32_t v21 = v20 + 8; // 0x19d8
                int32_t v22 = *(int32_t *)v21; // 0x19db
                if (v22 == 0) {
                    // 0x1a00
                    v17 = v2 + (int32_t)&g6 + 204;
                    goto lab_0x1a06;
                }
                v20 = v21;
                *(int32_t *)(v7 - 12) = v16;
                *(int32_t *)(v7 - 16) = v22;
            }
            // 0x19f2
            v17 = v20 + 4;
            goto lab_0x1a06;
        }
    }
  lab_0x1a06:;
    int32_t v23 = v8;
    int32_t v24 = *(int32_t *)v23; // 0x1a0c
    int32_t v25 = v23 + 4; // 0x1a0e
    int32_t v26 = v24 - 0x1010101 & (v24 ^ -0x7f7f7f80); // 0x1a19
    uint32_t v27 = v26 & -0x7f7f7f80; // 0x1a1b
    while (v27 == 0) {
        // 0x1a0c
        v23 = v25;
        v24 = *(int32_t *)v23;
        v25 = v23 + 4;
        v26 = v24 - 0x1010101 & (v24 ^ -0x7f7f7f80);
        v27 = v26 & -0x7f7f7f80;
    }
    unsigned char v28 = (char)((v26 & 0x8080) == 0 ? v27 / 0x10000 : v27); // 0x1a37
    int32_t v29 = -1 - v28 < v28 ? 4 : 3; // 0x1a3f
    int32_t * v30 = (int32_t *)(v7 - 16); // 0x1a45
    *v30 = *(int32_t *)v17;
    *(int32_t *)(v7 - 20) = v2 + (int32_t)&g6 - 0x2062;
    *(int32_t *)(v7 - 24) = -1;
    *(int32_t *)(v7 - 28) = 1;
    *(int32_t *)(v7 - 32) = ((v26 & 0x8080) == 0 ? v23 + 6 : v25) - v29;
    function_b90();
    int32_t v31 = v8;
    int32_t v32 = *(int32_t *)v31; // 0x1a57
    int32_t v33 = v31 + 4; // 0x1a59
    int32_t v34 = v32 - 0x1010101 & (v32 ^ -0x7f7f7f80); // 0x1a64
    uint32_t v35 = v34 & -0x7f7f7f80; // 0x1a66
    while (v35 == 0) {
        // 0x1a57
        v31 = v33;
        v32 = *(int32_t *)v31;
        v33 = v31 + 4;
        v34 = v32 - 0x1010101 & (v32 ^ -0x7f7f7f80);
        v35 = v34 & -0x7f7f7f80;
    }
    unsigned char v36 = (char)((v34 & 0x8080) == 0 ? v35 / 0x10000 : v35); // 0x1a82
    int32_t * v37 = (int32_t *)(v7 - 8); // 0x1a92
    *v37 = ((v34 & 0x8080) == 0 ? v31 + 6 : v33) - v8 + (-1 - v36 < v36 ? -4 : -3);
    int32_t * v38 = (int32_t *)(v7 - 12); // 0x1a93
    *v38 = v8;
    *v30 = a1;
    writen((int32_t)&g12, (int32_t)&g12, (int32_t)&g12);
    uint32_t v39 = *v4; // 0x1aa5
    uint32_t v40 = *(int32_t *)(v1 + (int32_t)&g3); // 0x1aab
    int32_t v41 = v39; // bp-292, 0x1ab3
    if (v40 > v39) {
        // 0x1ad8
        *(int32_t *)(v7 - 4) = v40 - v39;
        *v37 = (int32_t)&v41;
        *v38 = a2;
        *v30 = a1;
        if (function_a30(v41) >= 1) {
            // 0x1af4
            *v37 = v41;
            *v38 = v2 + (int32_t)&g6 - 0x204d;
            *v30 = 1;
            function_b00();
            *v30 = a1;
            function_b70();
        }
    }
    int32_t result = __readgsdword(20) ^ v3; // 0x1abe
    if (result != 0) {
        // 0x1b75
        return __stack_chk_fail_local();
    }
    // 0x1acb
    return result;
}

// Address range: 0x1b80 - 0x1d40
int32_t process(int32_t a1, int32_t a2) {
    // 0x1b80
    int32_t v1; // 0x1b80
    int32_t v2 = v1;
    __x86_get_pc_thunk_bx(v2);
    function_a00(__readgsdword(20));
    function_b00();
    int32_t v3; // bp-552, 0x1b80
    parse_request(a1, &v3);
    int32_t v4 = function_a50(&v3, 0, 0); // 0x1be1
    int32_t v5; // bp-668, 0x1b80
    int32_t v6 = &v5; // 0x1be6
    int32_t * v7; // 0x1b80
    int32_t v8; // 0x1b80
    if (v4 < 1) {
        // 0x1ce0
        client_error(a1, (int32_t *)"GNU", v2 + (int32_t)&g5 - 0x2030, v2 + (int32_t)&g5 - 0x203f);
        v7 = (int32_t *)(v6 - 16);
        v8 = (int32_t)"GNU";
    } else {
        // 0x1bf1
        function_a10((int32_t *)3);
        int32_t v9; // 0x1b80
        int32_t v10; // 0x1b80
        switch ((int16_t)v10 & -0x1000) {
            case -0x8000: {
                // 0x1c90
                serve_static(a1, v4, &v3, v1);
                v9 = v1 < 1 ? 200 : 206;
                // break -> 0x1c48
                break;
            }
            case 0x4000: {
                // 0x1d10
                handle_directory_request(a1, v4, &v3);
                v9 = 200;
                // break -> 0x1c48
                break;
            }
            default: {
                // 0x1c21
                client_error(a1, &g1, v2 + (int32_t)&g5 - 0x201f, v2 + (int32_t)&g5 - 0x2026);
                v9 = &g1;
                // break -> 0x1c48
                break;
            }
        }
        int32_t * v11 = (int32_t *)(v6 + 12); // 0x1c48
        *v11 = v9;
        int32_t * v12 = (int32_t *)(v6 - 16);
        *v12 = v4;
        function_b70();
        v7 = v12;
        v8 = *v11;
    }
    // 0x1c5c
    *(int32_t *)(v6 - 8) = (int32_t)&v3;
    *(int32_t *)(v6 - 12) = a2;
    *v7 = v8;
    log_access((int32_t)&g12, (int32_t)&g12, (int32_t)&g12);
    int32_t result = __readgsdword(20) ^ *(int32_t *)(v6 + 636); // 0x1c71
    if (result != 0) {
        // 0x1d2e
        return __stack_chk_fail_local();
    }
    // 0x1c7e
    return result;
}

// Address range: 0x1d40 - 0x1d9d
int32_t __libc_csu_init(int32_t a1) {
    // 0x1d40
    int32_t v1; // 0x1d40
    __x86_get_pc_thunk_bx(v1);
    _init();
    if ((int32_t)&g4 - 252 + 256 - (int32_t)&g4 >> 2 == 0) {
        // 0x1d95
        return v1 + (int32_t)&g4 - 256;
    }
    // 0x1d78
    int32_t v2; // bp-28, 0x1d40
    int32_t v3 = &v2; // 0x1d4f
    int32_t v4 = 0; // 0x1d8b
    *(int32_t *)(v3 - 8) = a1;
    *(int32_t *)(v3 - 12) = *(int32_t *)(v3 + 36);
    *(int32_t *)(v3 - 16) = *(int32_t *)(v3 + 32);
    while (v4 + 1 != (int32_t)&g4 - 252 + 256 - (int32_t)&g4 >> 2) {
        // 0x1d78
        v4++;
        *(int32_t *)(v3 - 8) = a1;
        *(int32_t *)(v3 - 12) = *(int32_t *)(v3 + 36);
        *(int32_t *)(v3 - 16) = *(int32_t *)(v3 + 32);
    }
    // 0x1d95
    return v1 + (int32_t)&g4 - 256;
}

// Address range: 0x1da0 - 0x1da2
int32_t __libc_csu_fini(void) {
    // 0x1da0
    int32_t result; // 0x1da0
    return result;
}

// Address range: 0x1db0 - 0x1dc4
int32_t __stack_chk_fail_local(void) {
    // 0x1db0
    int32_t v1; // 0x1db0
    __x86_get_pc_thunk_bx(v1);
    return function_9d0();
}

// Address range: 0x1dc4 - 0x1dd8
int32_t _fini(void) {
    // 0x1dc4
    int32_t v1; // 0x1dc4
    return __x86_get_pc_thunk_bx(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 63

