//
// This file was generated by the Retargetable Decompiler
// Website: https://retdec.com
// Copyright (c) Retargetable Decompiler <info@retdec.com>
//

#include <stdint.h>

// ------------------- Function Prototypes --------------------

int32_t entry_point(int32_t a1);
int32_t function_540(void);
int32_t function_580(int32_t * a1, int32_t * a2);
int32_t function_590(int32_t a1, int32_t * a2);
int32_t function_5a0(int32_t * a1);
int32_t function_5b0(void);
int32_t function_5c0(int32_t a1);
int32_t function_5d0(int32_t a1, int32_t a2);
int32_t function_5e0(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5);
int32_t function_5f0(int32_t a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_600(int32_t a1);
int32_t function_608(int32_t * a1, int32_t a2, int32_t a3, int32_t a4);
int32_t function_610(int32_t a1);
int32_t function_618(void);
int32_t function_652(int32_t a1, int32_t * a2, int32_t a3);
int32_t function_660(int32_t a1);
int32_t function_670(void);
int32_t function_6b0(void);
int32_t function_700(void);
int32_t function_750(void);
int32_t function_759(int32_t a1);
int32_t function_75d(int32_t a1);
int32_t function_980(int32_t a1);
int32_t function_9e0(void);
int32_t function_9f0(void);
int32_t function_a04(void);

// --------------------- Global Variables ---------------------

int32_t g1;

// ------------------------ Functions -------------------------

// Address range: 0x540 - 0x563
int32_t function_540(void) {
    // 0x540
    int32_t v1; // 0x540
    function_660(v1);
    int32_t result = 0; // 0x557
    if (*(int32_t *)(v1 + 0x1aa3) != 0) {
        // 0x559
        result = function_618();
    }
    // 0x55e
    return result;
}

// Address range: 0x580 - 0x586
int32_t function_580(int32_t * a1, int32_t * a2) {
    // 0x580
    int32_t result; // 0x580
    return result;
}

// Address range: 0x590 - 0x596
int32_t function_590(int32_t a1, int32_t * a2) {
    // 0x590
    int32_t result; // 0x590
    return result;
}

// Address range: 0x5a0 - 0x5a6
int32_t function_5a0(int32_t * a1) {
    // 0x5a0
    int32_t result; // 0x5a0
    return result;
}

// Address range: 0x5b0 - 0x5b6
int32_t function_5b0(void) {
    // 0x5b0
    int32_t result; // 0x5b0
    return result;
}

// Address range: 0x5c0 - 0x5c6
int32_t function_5c0(int32_t a1) {
    // 0x5c0
    int32_t result; // 0x5c0
    return result;
}

// Address range: 0x5d0 - 0x5d6
int32_t function_5d0(int32_t a1, int32_t a2) {
    // 0x5d0
    int32_t result; // 0x5d0
    return result;
}

// Address range: 0x5e0 - 0x5e6
int32_t function_5e0(int32_t a1, int32_t a2, int32_t * a3, int32_t a4, int32_t a5) {
    // 0x5e0
    int32_t result; // 0x5e0
    return result;
}

// Address range: 0x5f0 - 0x5f6
int32_t function_5f0(int32_t a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x5f0
    int32_t result; // 0x5f0
    return result;
}

// Address range: 0x600 - 0x606
int32_t function_600(int32_t a1) {
    // 0x600
    int32_t result; // 0x600
    return result;
}

// Address range: 0x608 - 0x60e
int32_t function_608(int32_t * a1, int32_t a2, int32_t a3, int32_t a4) {
    // 0x608
    int32_t result; // 0x608
    return result;
}

// Address range: 0x610 - 0x616
int32_t function_610(int32_t a1) {
    // 0x610
    int32_t result; // 0x610
    return result;
}

// Address range: 0x618 - 0x61e
int32_t function_618(void) {
    // 0x618
    int32_t result; // 0x618
    return result;
}

// Address range: 0x620 - 0x652
int32_t entry_point(int32_t a1) {
    // 0x620
    int32_t v1; // 0x620
    int32_t v2 = v1;
    int32_t v3; // bp-4, 0x620
    function_652(v1, &v3, v1);
    int32_t v4; // 0x620
    function_5e0(*(int32_t *)(v2 + 0x19c8), a1, &v4, v2 + 848, v2 + 944);
    __asm_hlt();
    // UNREACHABLE
}

// Address range: 0x652 - 0x656
int32_t function_652(int32_t a1, int32_t * a2, int32_t a3) {
    // 0x652
    int32_t result; // 0x652
    return result;
}

// Address range: 0x660 - 0x664
int32_t function_660(int32_t a1) {
    // 0x660
    int32_t result; // 0x660
    return result;
}

// Address range: 0x670 - 0x6aa
int32_t function_670(void) {
    // 0x670
    function_759((int32_t)&g1);
    int32_t v1; // 0x670
    return v1 + 0x1993;
}

// Address range: 0x6b0 - 0x6f7
int32_t function_6b0(void) {
    // 0x6b0
    function_759((int32_t)&g1);
    return 0;
}

// Address range: 0x700 - 0x747
int32_t function_700(void) {
    // 0x700
    int32_t v1; // 0x700
    int32_t result = function_660(v1); // 0x704
    char * v2 = (char *)(v1 + 0x18ff); // 0x712
    if (*v2 != 0) {
        // 0x742
        return result;
    }
    // 0x71b
    if (*(int32_t *)(v1 + 0x18d3) != 0) {
        // 0x725
        function_600(*(int32_t *)(v1 + 0x18fb));
    }
    int32_t result2 = function_670(); // 0x736
    *v2 = 1;
    // 0x742
    return result2;
}

// Address range: 0x750 - 0x759
int32_t function_750(void) {
    // 0x750
    return function_6b0();
}

// Address range: 0x759 - 0x75d
int32_t function_759(int32_t a1) {
    // 0x759
    int32_t result; // 0x759
    return result;
}

// Address range: 0x75d - 0x97f
int32_t function_75d(int32_t a1) {
    // 0x75d
    int32_t v1; // 0x75d
    int32_t v2 = v1;
    int32_t v3; // 0x75d
    function_660((int32_t)&v3);
    int32_t v4 = __readgsdword(20); // 0x77e
    function_5f0(*(int32_t *)*(int32_t *)(v2 + 0x187c), 0, 2, 0);
    function_5f0(*(int32_t *)*(int32_t *)(v2 + 0x1860), 0, 2, 0);
    int32_t v5; // bp-556, 0x75d
    __asm_rep_stosd_memset((char *)&v5, 0, 66);
    int32_t v6 = function_5d0(0, v2 + 680); // 0x7d7
    int32_t v7; // bp-292, 0x75d
    __asm_rep_stosd_memset((char *)&v7, 0, 64);
    function_590(v2 + 683, &v7);
    function_590(v2 + 697, (int32_t *)*(int32_t *)(v2 + 0x186c));
    function_590(v2 + 711, (int32_t *)*(int32_t *)(v2 + 0x1870));
    function_590(v2 + 725, (int32_t *)*(int32_t *)(v2 + 0x1868));
    function_610(v2 + 740);
    if (function_5f0(*(int32_t *)*(int32_t *)(v2 + 0x1878), 0, 2, 0) != 0) {
        // 0x8a0
        function_5c0(v2 + 817);
    }
    // 0x8b2
    function_5a0(&v5);
    function_610(v2 + 834);
    int32_t v8; // 0x75d
    if (function_608(&v7, 256, 1, v6) != 0) {
        // 0x91b
        if (function_580(&v5, &v7) != 0) {
            // 0x94c
            function_610(v2 + 896);
            v8 = 0;
        } else {
            // 0x938
            function_610(v2 + 876);
            v8 = 0;
        }
    } else {
        // 0x902
        function_5c0(v2 + 861);
        v8 = -1;
    }
    int32_t result = v8; // 0x96d
    if (v4 != __readgsdword(20)) {
        // 0x96f
        result = function_9f0();
    }
    // 0x974
    return result;
}

// Address range: 0x980 - 0x9dd
int32_t function_980(int32_t a1) {
    // 0x9d5
    int32_t v1; // 0x980
    function_660(v1);
    int32_t v2; // bp-28, 0x980
    int32_t v3 = &v2; // 0x98f
    function_540();
    *(int32_t *)(v3 - 8) = a1;
    *(int32_t *)(v3 - 12) = *(int32_t *)(v3 + 36);
    *(int32_t *)(v3 - 16) = *(int32_t *)(v3 + 32);
    return v1 + 0x151f;
}

// Address range: 0x9e0 - 0x9e2
int32_t function_9e0(void) {
    // 0x9e0
    int32_t result; // 0x9e0
    return result;
}

// Address range: 0x9f0 - 0xa04
int32_t function_9f0(void) {
    // 0x9f0
    int32_t v1; // 0x9f0
    function_660(v1);
    return function_5b0();
}

// Address range: 0xa04 - 0xa18
int32_t function_a04(void) {
    // 0xa04
    int32_t v1; // 0xa04
    return function_660(v1);
}

// --------------------- Meta-Information ---------------------

// Detected compiler/packer: gcc (7.5.0)
// Detected functions: 26

